[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/treelab/_version.py"

[project]
name = "mola-treelab"
license = { text = "LGPL-3.0-only" }
dynamic = ["version"]
authors = [
  { name="Luis Bernardos", email="luisfco.bernardos@gmail.com" },
  { name="Thomas Bontemps", email="thomas.bontemps@hotmail.fr" }
]
description = "MOLA-treelab is an ONERA code that implements an interface to CGNS"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy>=1.21.0",
  "noder>=1.2.0",
  "pyqtgraph>=0.14.0; python_version >= '3.10'",
  "pyqtgraph>=0.13.2,<0.14.0; python_version < '3.10'",
  "pyside6; python_version >= '3.10'",
  "pyside6>=6.2,<6.6; python_version < '3.10'",
]

[project.optional-dependencies]
test = [
  "pytest",
]

[project.urls]
Homepage = "https://github.com/Luispain/treelab"
Issues = "https://github.com/Luispain/treelab/issues"

[project.gui-scripts]
treelab = "treelab.gui.main:launch"

[tool.hatch.build]
include = ["LICENSE"]

[tool.hatch.build.targets.wheel]
packages = ["src/treelab"]
