name: Test & Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Hatch and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Run tests
        run: hatch run test  # <-- or update this to your test command

  deploy:
    name: Build and upload to PyPI
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install hatch twine

      - name: Build the package
        run: hatch build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
