name: Build and publish pure Python package

on:
  push:
    tags:
      - "v*"

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install hatch twine pytest

      - name: Run tests
        run: |
          pip install .[test]
          pytest

      - name: Build universal wheel
        run: hatch build

      - name: Upload to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
